# /SIAE_DEV/docker-compose.yml

version: '3.8'

services:

  # ... (El servicio 'db' de Postgres va aquí, igual que antes)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: $siae_admin
      POSTGRES_PASSWORD: $admin123
      POSTGRES_DB: $siae_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- Servicio de Backend (FastAPI) ---
  backend:
    container_name: fastapi_backend
    # Ruta de construcción ajustada a tu carpeta
    build: ./Fast_API
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Mapeo de volumen ajustado a tu carpeta
      - ./Fast_API:/app
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      - db

  # ... (El servicio 'frontend' de React va aquí, igual que antes)
  frontend:
    container_name: react_frontend
    build: ./frontend # Asumiendo que tu frontend está en /SIAE_DEV/frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: